import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <div className="container">
            <Link className="logo" href="/">
              syedmh
            </Link>
            <nav>
              <ul>
                <li>
                  <a href="/blog">blog</a>
                </li>
                <li>
                  <a href="/work">work</a>
                </li>
                <li>
                  <a href="/contact">contact</a>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main className="container">{children}</main>
        <footer>
          <div className="container">
            <div>
              <h2>Get in touch with me</h2>
              <a href="mailto:contactsyedmh@gmail.com">
                contactsyedmh@gmail.com
              </a>
            </div>
            <div className="navigation">
              <h2>Useful links</h2>
              <ul>
                <li>
                  <a href="_#">Learning resources</a>
                </li>
                <li>
                  <a href="_#">Inspiration</a>
                </li>
                <li>
                  <a href="_#">Podcasts</a>
                </li>
                <li>
                  <a href="_#">People</a>
                </li>
                <li>
                  <a href="_#">Older work</a>
                </li>
                <li>
                  <a href="_#">Older blogs</a>
                </li>
                <li>
                  <a href="_#">About me</a>
                </li>
                <li>
                  <a href="_#">About this site</a>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
